# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoteEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Remark(object):
    def setupUi(self, Remark):
        Remark.setObjectName("Remark")
        Remark.resize(556, 394)
        self.CommitNote = QtWidgets.QDialogButtonBox(Remark)
        self.CommitNote.setGeometry(QtCore.QRect(180, 340, 341, 32))
        self.CommitNote.setOrientation(QtCore.Qt.Horizontal)
        self.CommitNote.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CommitNote.setObjectName("CommitNote")
        self.NoteContent = QtWidgets.QTextEdit(Remark)
        self.NoteContent.setGeometry(QtCore.QRect(30, 80, 491, 231))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.NoteContent.setFont(font)
        self.NoteContent.setObjectName("NoteContent")
        self.label = QtWidgets.QLabel(Remark)
        self.label.setGeometry(QtCore.QRect(30, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Remark)
        self.CommitNote.accepted.connect(Remark.accept)
        self.CommitNote.rejected.connect(Remark.reject)
        QtCore.QMetaObject.connectSlotsByName(Remark)

    def retranslateUi(self, Remark):
        _translate = QtCore.QCoreApplication.translate
        Remark.setWindowTitle(_translate("Remark", "Dialog"))
        self.NoteContent.setHtml(_translate("Remark", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Remark", "请输入备注："))

