# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TitleEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 199)
        self.CommitTitle = QtWidgets.QDialogButtonBox(Dialog)
        self.CommitTitle.setGeometry(QtCore.QRect(100, 150, 341, 32))
        self.CommitTitle.setOrientation(QtCore.Qt.Horizontal)
        self.CommitTitle.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CommitTitle.setObjectName("CommitTitle")
        self.TitleContent = QtWidgets.QTextEdit(Dialog)
        self.TitleContent.setGeometry(QtCore.QRect(40, 80, 401, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.TitleContent.setFont(font)
        self.TitleContent.setObjectName("TitleContent")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 461, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.CommitTitle.accepted.connect(Dialog.accept)
        self.CommitTitle.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "请输入标题：（最多16字，禁止轻小说式超长标题）"))
